name: Deploy Expense Tracker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          timeout: 60s
          command_timeout: 15m

          script: |
            echo "========== Deploy Started =========="

            # Create directory if it doesn't exist
            sudo mkdir -p /var/www/expense-tracker

            # Change ownership
            sudo chown -R $USER:$USER /var/www/expense-tracker

            # Go to project folder
            cd /var/www/expense-tracker

            # If not cloned already, clone the repository
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            fi

            # Get latest code
            git fetch origin main
            git reset --hard origin/main

            # Fix permissions
            sudo chmod -R 755 /var/www/expense-tracker

            # Reload Nginx
            sudo systemctl reload nginx

            echo "========== Deployment Successful =========="

            echo "Current Commit:"
            git rev-parse --short HEAD